name: PonyRaceAPI_Example
version: '1.0'
main: fun.eqad.ponyraceapi_example.PonyRace_Example
api-version: '1.20'
author: EQAD Network
depend:
  - PonyRace
commands:
  prtest:
    description: PonyRace API
    usage: /prtest [info|setrace|setmana|setstamina|setenrage]